### ISSUE TITLE
hinotify-0.3.8 fails in stackage nightly

### ISSUE THREAD

**Issue by juhp** [kolmodin/hinotify#15]
```
Configuring hinotify-0.3.8...
Building hinotify-0.3.8...
Preprocessing library hinotify-0.3.8...
[1 of 2] Compiling System.INotify.Masks ( dist/build/System/INotify/Masks.hs, dist/build/System/INotify/Masks.o )
[2 of 2] Compiling System.INotify   ( dist/build/System/INotify.hs, dist/build/System/INotify.o )
In-place registering hinotify-0.3.8...
Preprocessing test suite 'test001' for hinotify-0.3.8...

tests/test001-list-dir-contents.hs:9:8:
    Could not find module ‘Utils’
    it is a hidden module in the package ‘process-extras-0.3.3.5@proce_4E5CwQ75w4R6n57Qyz95CI’
    it is a hidden module in the package ‘concurrent-extra-0.7.0.9@concu_68QJwHhXQuKAFJ6sd9YyAB’
    Use -v to see a list of the files searched for.
```

**Comment by peti** [comment]
NixOS has the same problem: http://hydra.cryp.to/build/1054603/nixlog/1/raw. The release tarball appears to be incomplete.

**Comment by kolmodin** [comment]
Thanks for the report! Somehow this slipped through travis.
I'm testing the fix...

**Comment by kolmodin** [comment]
Fixed in efdc59b8a456bff7aeefd666c4cb59159fc3af54. The Utils module was not listed as a dependency anywhere, so it didn't get included in 'cabal sdist'.
Somehow Travis could still build the tarball, not sure why.

**Comment by kolmodin** [comment]
Also... I've released `hinotify 0.3.8.1`.

**Comment by peti** [comment]
> Somehow Travis could still build the tarball, not sure why.

`cabal install` from your travis recipe does not try to build the test suite, so the error remained unnoticed.

**Comment by kolmodin** [comment]
OK, from now the tests will be built as well.
